### ISSUE TITLE
Document ability to style refs

### ISSUE THREAD

**Issue by TehShrike** [sveltejs/svelte.technology#249]
I learned about this feature from https://gist.github.com/Rich-Harris/351ec2fc4fcf375d2c8e9090620a8bed#file-scroller-html-L16-L29

```css
  ref:outer {
    position: relative;
  }
```
